vpn-provider: Make reset_error_counters() static
Declare reset_error_counters() as static as it should not be
used in other contexts.

Get rid of this error from GCC 9.1.0:

vpn/vpn-provider.c:865:6: error: no previous declaration for
‘reset_error_counters’ [-Werror=missing-declarations]
  865 | void reset_error_counters(struct vpn_provider *provider)