inet: Remove unused ipv6_addr_advert_mult
clang complains with

src/inet.c:1839:20: error: unused function 'ipv6_addr_advert_mult' [-Werror,-Wunused-function]
static inline void ipv6_addr_advert_mult(const struct in6_addr *addr,
                   ^
Remove the ipv6_addr_advert_mult function.