unit: Fix missing declarations in test-iptables
gcc reports with:

 unit/test-iptables.c:72:5: error: no previous declaration for 'xt_match_parse' [-Werror=missing-declarations]
   72 | int xt_match_parse(int c, char **argv, int invert, unsigned int *flags,
      |     ^~~~~~~~~~~~~~
 unit/test-iptables.c:78:5: error: no previous declaration for 'xt_target_parse' [-Werror=missing-declarations]
   78 | int xt_target_parse(int c, char **argv, int invert, unsigned int *flags,
      |     ^~~~~~~~~~~~~~~