error: Handle EPERM as PermissionDenied D-Bus error
PermissionDenied error must be sent also when EPERM is the errorcode.
This is used in vpn-provider.c to indicate that property to be changed
or cleared is immutable and cannot be changed. This change ensures that
the replied error message corresponds to the situation.