session-utils: Remove -Wcast-function-type from build
Newer versions of gcc (8.1) are very pendantic:

tools/session-utils.c: In function ‘util_test_add’:
tools/session-utils.c:234:4: error: cast between incompatible function types from ‘void (*)(const void *)$
    (GTestFixtureFunc) run_test_cb,
tools/session-utils.c:235:4: error: cast between incompatible function types from ‘void (*)(void *)’ to ‘$
    (GTestFixtureFunc) g_free);

Reported by Ross Burton.

(cherry picked from commit 84984e919ab7e5fd804b452ea60dd7e37c37278f)